### ISSUE TITLE
setList* 以外のsetsがリストアップされない

### ISSUE THREAD

**Issue by teionn** [3dManu/setsList#1]
普通に作ったsetsがリストアップされない
ネーミングがsetList* 以外のsetもリストアップして欲しい

![2018-05-18 11_07_02-autodesk maya 2017_ untitled_](https://user-images.githubusercontent.com/19668775/40212616-cfb55050-5a8b-11e8-95e3-62105b9e051a.png)

**Comment by 3dManu** [comment]
自分で作成したsetをリストに追加するには、アウトライナから追加したいsetを選択してから上にある[Add]ボタンを押せば追加できます！
リストに追加するかしないかの判定はsetNodeにあるtextで判別しているので、もしtextの中身を変えたくない状態がある場合は別の方法を考えます！

**Comment by teionn** [comment]
Sets選択 → Add で追加できました。

セットリスト説明.pngの更新ありがとうございます。
分かりやすいです。
